CREATE TABLE USUARIOS (
    OID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DOCUMENTO VARCHAR(20) NOT NULL UNIQUE,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(10),
    CORREO VARCHAR(100),
    FECHA_NACIMIENTO DATE NOT NULL,
    ESTADO INT NOT NULL CHECK (ESTADO IN (0, 1)),
    FECHA_CREA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZA TIMESTAMP
);

CREATE TABLE PROFESIONAL (
    OID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    ESPECIALIDAD VARCHAR(50) NOT NULL,
    ESTADO INT NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE CITAS (
    OID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_OID INT NOT NULL,
    PROFESIONAL_OID INT NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    MOTIVO VARCHAR(255),
    ESTADO INT NOT NULL CHECK (ESTADO IN (1, 2, 3, 4)),
    FECHA_CREA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZA TIMESTAMP,

    CONSTRAINT FK_CITA_USUARIO
        FOREIGN KEY (USUARIO_OID)
        REFERENCES USUARIOS(OID),

    CONSTRAINT FK_CITA_PROFESIONAL
        FOREIGN KEY (PROFESIONAL_OID)
        REFERENCES PROFESIONAL(OID)
);

--RESTRICCION PARA QUE NO HAYAN DOS CITAS IGUALES
ALTER TABLE CITAS
ADD CONSTRAINT UQ_CITA_PROFESIONAL_FECHA_HORA
UNIQUE (PROFESIONAL_OID, FECHA, HORA);

CREATE TABLE ESTADOS (
    OID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ESTADO VARCHAR(20) NOT NULL
);

INSERT INTO ESTADOS (ESTADO)
VALUES
('ACTIVO'),
('INACTIVO'),
('PENDIENTE'),
('CONFIRMADO'),
('CANCELADO'),
('ATENDIDO');

INSERT INTO PROFESIONAL (
    NOMBRE,
    APELLIDO,
    ESPECIALIDAD,
    ESTADO
)
VALUES
('ROGER', 'LOAIZA', 'GINECOLOGIA', 1),
('DAHIANA', 'GRISALES', 'MEDICINA INTERNA', 1),
('ANDRES', 'OSPINA', 'CIRUGIA', 1),
('YEFERSON', 'DUQUE', 'PEDIATRIA', 1);





